"""
Transcript search tool implementation.

This tool searches through the patient transcript for relevant information
using fuzzy matching (same approach as search_patient_notes).
"""

import json
import logging
from collections.abc import AsyncGenerator
from typing import Any

from server.utils.chat.streaming.response import (
    end_message,
    status_message,
)
from server.utils.chat.tools.search_patient_notes import find_matches_in_text

logger = logging.getLogger(__name__)

MAX_RESULTS = 15


async def execute(
    tool_call: dict[str, Any],
    _llm_client,
    _config: dict[str, Any],
    _message_list: list,
    _conversation_history: list,
    raw_transcription: str | None,
    _context_question_options: dict[str, Any],
) -> AsyncGenerator[dict[str, Any], None]:
    """
    Execute the transcript search tool using fuzzy matching.

    Args:
        tool_call: The tool call to execute.
        _llm_client: Unused (kept for signature compatibility with executor).
        _config: Unused.
        _message_list: Unused.
        _conversation_history: Unused.
        raw_transcription: The raw transcript text.
        _context_question_options: Unused.

    Yields:
        Dict[str, Any]: Streaming response chunks.
    """
    logger.info("Executing transcript_search tool...")

    # Guard: no transcript
    if not raw_transcription:
        logger.info("No transcript available.")
        yield status_message("Generating response...")
        yield end_message(
            function_response={
                "content": "No transcript is available to search. "
                "Please answer the user's question without transcript information."
            }
        )
        return

    yield status_message("Searching transcript...")

    # Parse function arguments
    function_arguments = {}
    if "arguments" in tool_call["function"]:
        try:
            if isinstance(tool_call["function"]["arguments"], str):
                function_arguments = json.loads(tool_call["function"]["arguments"])
            else:
                function_arguments = tool_call["function"]["arguments"]
        except json.JSONDecodeError:
            logger.error("Failed to parse transcript_search arguments")

    search_terms = function_arguments.get("search_term")

    # Guard: no search term
    if not search_terms:
        yield end_message(
            function_response={"content": "Please provide a search_term to search the transcript."}
        )
        return

    if isinstance(search_terms, str):
        search_terms = [search_terms]

    # Search for each term and collect matches
    all_matches = []
    seen_contexts = set()

    for term in search_terms:
        matches = find_matches_in_text(raw_transcription, term, context_window=1)
        for match in matches:
            # Deduplicate by context text
            context_key = match["context"][:100].lower().strip()
            if context_key not in seen_contexts:
                seen_contexts.add(context_key)
                all_matches.append({"term": term, **match})

    # Guard: no matches
    if not all_matches:
        terms_str = ", ".join(f"'{t}'" for t in search_terms)
        yield end_message(
            function_response={"content": f"No matches found for {terms_str} in the transcript."}
        )
        return

    # Sort by score descending, take top results
    all_matches.sort(key=lambda m: m["score"], reverse=True)
    top_matches = all_matches[:MAX_RESULTS]

    # Format response grouped by search term
    parts = [f"Found {len(top_matches)} match(es) in the transcript:\n"]

    for i, match in enumerate(top_matches, 1):
        parts.append(f'  {i}. [{match["term"]}] (score: {match["score"]}) "{match["context"]}"')

    parts.append(
        "\nNote: The transcript was generated by an automated system and may contain errors."
    )

    result_content = "\n".join(parts)
    logger.info(f"Transcript search returned {len(top_matches)} matches")

    yield end_message(function_response={"content": result_content})
